# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.


version: '3.4'


#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:
 
services:
  create:
    build:
      context: ./createapi #write your api name here
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "5080:80"
    restart: always
    #Specify Environment Variables for the Api Service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
